import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().required(),
  SWAGGER_TITLE: Joi.string().required(),
  SWAGGER_DESCRIPTION: Joi.string().required(),
  SWAGGER_VERSION: Joi.string().required(),
  CORS_ORIGIN: Joi.string().default('*'),
  SMTP_HOST: Joi.string().allow('').default(''),
  SMTP_PORT: Joi.number().default(587),
  SMTP_SECURE: Joi.boolean().default(false),
  SMTP_USER: Joi.string().allow('').default(''),
  SMTP_PASS: Joi.string().allow('').default(''),
  SMTP_FROM_EMAIL: Joi.string().allow('').default(''),
  SMTP_FROM_NAME: Joi.string().allow('').default('EduFlow'),
  WHATSAPP_CALLMEBOT_API_KEY: Joi.string().allow('').default(''),
  OPENAI_API_KEY: Joi.string().allow('').default(''),
  OPENAI_MODEL: Joi.string().allow('').default('gpt-4o-mini'),
  GROQ_API_KEY: Joi.string().allow('').default(''),
  GROQ_MODEL: Joi.string().allow('').default('llama-3.1-8b-instant'),
  GROQ_TRIAL_REQUEST_LIMIT: Joi.number().integer().min(1).default(5),
  ONLINE_CLASSES_ENABLED: Joi.boolean().default(false),
  ORGANIZATION_SECRET_KEY: Joi.string().allow('').default(''),
  GOOGLE_WORKSPACE_CLIENT_EMAIL: Joi.string().allow('').default(''),
  GOOGLE_WORKSPACE_PRIVATE_KEY: Joi.string().allow('').default(''),
  GOOGLE_WORKSPACE_PROJECT_ID: Joi.string().allow('').default(''),
  GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL: Joi.string().allow('').default(''),
  GOOGLE_WORKSPACE_DEFAULT_CALENDAR_ID: Joi.string().allow('').default('primary'),
});
